# # Playbook is list of plays, always it should start with -
- name: installing nginx and start
  hosts: mongodb
  become: yes
  tasks:
  - name: installing nginx
    yum:
      name: nginx
      state: installed
  - name: starting nginx
    service:
      name: nginx
      state: started