- name: checking user exist dynamically
  hosts: localhost
  vars_prompt:
    - name: user
      prompt: Enter user name
      private: false
  tasks:
  - name: checking user
    command: id {{user}}
    register: u
    ignore_errors: true
  - name: printing user
    debug:
      msg: "User is : {{user}}"
  - name: printing user exit status
    debug:
      msg: "user exit status: {{u.rc}}"
  - name: creating user if not existed
    user:
      name: "{{user}}"
    when: u.rc != 0
