- name: variables at tasks
  hosts: localhost
  vars:
    Name: kiran
    packages:
      - mailx
      - mysql
  tasks:
  - name: printing task level variables along with play 
    vars:
      city: Bangalore
      age: 33
    ansible.builtin.debug:
      msg: "Name is : {{Name}}, city is : {{city}} & age is : {{age}}"
  - name: printing List variables
    ansible.builtin.debug:
      msg: "packages list is : {{packages}}"