- name: loop conditions 
  hosts: localhost
  vars:
    packages:
      mailx
      nginx
      tomcat
  tasks:
  - name: printing List with loop
    ansible.builtin.debug:
      msg: " packages: {{packages}}"
  - name: printing List with loop
    ansible.builtin.debug:
      msg: " package: {{item}}"
    loop:
      packages