- name: install packages
  hosts: localhost
  become: yes
  packages:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    # list of string
    loop: "{{packages}}"
   