- name: installing packages
  hosts: localhost
  become: yes
  vars:
    packages:
      - nginx
      - postfix
      - cyrus-sasl-plain
      - mailx
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item}}"
      # state: installed
      state:  absent
    # list of string
    loop: "{{packages}}"
   